//
// File generated by /nfs/cern/root5.26_x64/bin/rootcint at Mon Apr  1 15:49:54 2013

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "RooJpsiJpsiFitCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void RooJpsiJpsiFit_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void RooJpsiJpsiFit_Dictionary();
   static void *new_RooJpsiJpsiFit(void *p = 0);
   static void *newArray_RooJpsiJpsiFit(Long_t size, void *p);
   static void delete_RooJpsiJpsiFit(void *p);
   static void deleteArray_RooJpsiJpsiFit(void *p);
   static void destruct_RooJpsiJpsiFit(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::RooJpsiJpsiFit*)
   {
      ::RooJpsiJpsiFit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::RooJpsiJpsiFit),0);
      static ::ROOT::TGenericClassInfo 
         instance("RooJpsiJpsiFit", "RooJpsiJpsiFit.hh", 33,
                  typeid(::RooJpsiJpsiFit), DefineBehavior(ptr, ptr),
                  0, &RooJpsiJpsiFit_Dictionary, isa_proxy, 0,
                  sizeof(::RooJpsiJpsiFit) );
      instance.SetNew(&new_RooJpsiJpsiFit);
      instance.SetNewArray(&newArray_RooJpsiJpsiFit);
      instance.SetDelete(&delete_RooJpsiJpsiFit);
      instance.SetDeleteArray(&deleteArray_RooJpsiJpsiFit);
      instance.SetDestructor(&destruct_RooJpsiJpsiFit);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::RooJpsiJpsiFit*)
   {
      return GenerateInitInstanceLocal((::RooJpsiJpsiFit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::RooJpsiJpsiFit*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void RooJpsiJpsiFit_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::RooJpsiJpsiFit*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_RooJpsiJpsiFit(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RooJpsiJpsiFit : new ::RooJpsiJpsiFit;
   }
   static void *newArray_RooJpsiJpsiFit(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RooJpsiJpsiFit[nElements] : new ::RooJpsiJpsiFit[nElements];
   }
   // Wrapper around operator delete
   static void delete_RooJpsiJpsiFit(void *p) {
      delete ((::RooJpsiJpsiFit*)p);
   }
   static void deleteArray_RooJpsiJpsiFit(void *p) {
      delete [] ((::RooJpsiJpsiFit*)p);
   }
   static void destruct_RooJpsiJpsiFit(void *p) {
      typedef ::RooJpsiJpsiFit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::RooJpsiJpsiFit

/********************************************************
* RooJpsiJpsiFitCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableRooJpsiJpsiFitCint();

extern "C" void G__set_cpp_environmentRooJpsiJpsiFitCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("RooJpsiJpsiFit.hh");
  G__cpp_reset_tagtableRooJpsiJpsiFitCint();
}
#include <new>
extern "C" int G__cpp_dllrevRooJpsiJpsiFitCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* RooJpsiJpsiFit */
static int G__RooJpsiJpsiFitCint_824_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RooJpsiJpsiFit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooJpsiJpsiFit[n];
     } else {
       p = new((void*) gvp) RooJpsiJpsiFit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RooJpsiJpsiFit;
     } else {
       p = new((void*) gvp) RooJpsiJpsiFit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((RooJpsiJpsiFit*) G__getstructoffset())->readData(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((RooJpsiJpsiFit*) G__getstructoffset())->readData(*(map<std::string,double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->plotData(*(map<std::string,double>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->PDFmaker(*(map<std::string,double>*) libp->para[0].ref, *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->pureMCtoysGeneration();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->fitData(*(map<std::string,double>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->embedMCtoysGeneration();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RooJpsiJpsiFitCint_824_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RooJpsiJpsiFit*) G__getstructoffset())->PlotEmbedMCtoys();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RooJpsiJpsiFitCint_824_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   RooJpsiJpsiFit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new RooJpsiJpsiFit(*(RooJpsiJpsiFit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RooJpsiJpsiFit G__TRooJpsiJpsiFit;
static int G__RooJpsiJpsiFitCint_824_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (RooJpsiJpsiFit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((RooJpsiJpsiFit*) (soff+(sizeof(RooJpsiJpsiFit)*i)))->~G__TRooJpsiJpsiFit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (RooJpsiJpsiFit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((RooJpsiJpsiFit*) (soff))->~G__TRooJpsiJpsiFit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__RooJpsiJpsiFitCint_824_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RooJpsiJpsiFit* dest = (RooJpsiJpsiFit*) G__getstructoffset();
   *dest = *(RooJpsiJpsiFit*) libp->para[0].ref;
   const RooJpsiJpsiFit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* RooJpsiJpsiFit */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncRooJpsiJpsiFitCint {
 public:
  G__Sizep2memfuncRooJpsiJpsiFitCint(): p(&G__Sizep2memfuncRooJpsiJpsiFitCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncRooJpsiJpsiFitCint::*p)();
};

size_t G__get_sizep2memfuncRooJpsiJpsiFitCint()
{
  G__Sizep2memfuncRooJpsiJpsiFitCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceRooJpsiJpsiFitCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableRooJpsiJpsiFitCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> > >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<RooAbsCache*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RooCurve*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_listlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<EvalError>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<RooAbsReal::EvalError>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::string,std::list<EvalError> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,std::pair<std::string,std::list<EvalError> > >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > > >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >,less<const RooAbsArg*> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<RooDataSet*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_listlERooDataSetmUcOallocatorlERooDataSetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::string>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string,less<int> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StreamConfig>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<RooMsgService::StreamConfig>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> > >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_dequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("stack<std::vector<StreamConfig> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_stacklEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOdequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("stack<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> > >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_stacklEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOdequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::ostream*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,basic_ostream<char,char_traits<char> >*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,basic_ostream<char,char_traits<char> >*,less<string> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RooCacheManager<std::vector<Double_t> >",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<RooArgSet*>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* RooJpsiJpsiFit */
static void G__setup_memvarRooJpsiJpsiFit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit));
   { RooJpsiJpsiFit *p; p=(RooJpsiJpsiFit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"_initDataVars=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dataVars)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooArgSet),-1,-1,1,"dataVars=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1_Mass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1_Mass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi2_Mass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi2_Mass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FourMu_CTxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"FourMu_CTxy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FourMu_pT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"FourMu_pT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1To2_S)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1To2_S=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1To2_dY)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1To2_dY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1To2DistT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1To2DistT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1To2DistTot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1To2DistTot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1To2Significance)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1To2Significance=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FourMu_Mass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"FourMu_Mass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PvN)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"PvN=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi1_CTxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi1_CTxy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Psi2_CTxy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Psi2_CTxy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->frac_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"frac_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->frac_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"frac_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_frac_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_frac_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_frac_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_frac_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_7)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_7=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_frac_8)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_frac_8=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_f)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_f)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_f)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_f)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_f)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi1_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"jpsi1_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi1_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"jpsi1_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"jpsi2_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"jpsi2_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jpsi2_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"jpsi2_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi1_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg_jpsi1_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi1_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg_jpsi1_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_jpsi2_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg_jpsi2_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_jpsi2_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg_jpsi2_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi1_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"Bbkg_jpsi1_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi1_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"Bbkg_jpsi1_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_mass_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_mass_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_mass_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_mass_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_mass_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_mass_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_width_1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_width_1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_width_2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_width_2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_width_3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_jpsi2_width_3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_width_a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"Bbkg_jpsi2_width_a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_jpsi2_width_b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"Bbkg_jpsi2_width_b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p0_jpsi1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p0_jpsi1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p1_jpsi1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p1_jpsi1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p2_jpsi1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p2_jpsi1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p0_jpsi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p0_jpsi2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p1_jpsi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p1_jpsi2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p0_jpsi1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p0_jpsi1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p1_jpsi1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p1_jpsi1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p0_jpsi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p0_jpsi2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p1_jpsi2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p1_jpsi2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p0_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p0_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p1_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p1_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p2_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p2_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p3_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p3_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p4_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p4_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p5_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p5_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p6_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p6_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p7_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p7_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p8_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p8_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_p9_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_p9_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p0_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p0_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p1_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p1_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p2_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p2_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p3_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p3_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p4_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p4_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p5_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p5_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_p6_distT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_p6_distT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->etab_lambda)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"etab_lambda=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_lambda1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_lambda1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_lambda2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_lambda2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_lambda)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_lambda=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_coreCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_coreCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_coreCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_coreCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_tailCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_tailCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_tailCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_tailCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_fracCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_fracCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_coreCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_coreCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_coreCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_coreCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_mean_tailCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_mean_tailCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_tailCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_sigma_tailCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_fracCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"R_fracCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_totCT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"R_sigma_totCT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R_sigma_totCT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"R_sigma_totCT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg1_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg1_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg1_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg1_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg1_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg1_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg1_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg1_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg1_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg1_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg2_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg3_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg3_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg3_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg3_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg3_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg3_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg3_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg3_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg3_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg3_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg4_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg4_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg4_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg4_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg4_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg4_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg4_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg4_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg4_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg4_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg7_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg7_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg7_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg7_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg7_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg7_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg7_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg7_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg7_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg7_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg8_R_mean_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg8_R_mean_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg8_R_sigma_core)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg8_R_sigma_core=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg8_R_mean_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg8_R_mean_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg8_R_sigma_tail)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg8_R_sigma_tail=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg8_R_sigma_tot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooFormulaVar),-1,-1,1,"bkg8_R_sigma_tot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_mean_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_mean_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_width_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_width_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_lambda_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_lambda_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_mean_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_mean_CT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_width_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_width_CT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bbkg_lambda_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"Bbkg_lambda_CT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_mean_CT1_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_mean_CT1_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_width_CT1_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_width_CT1_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda_CT1_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda_CT1_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_mean_CT2_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_mean_CT2_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_width_CT2_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_width_CT2_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda_CT2_SB1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda_CT2_SB1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_mean_CT1_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_mean_CT1_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_width_CT1_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_width_CT1_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda_CT1_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda_CT1_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_mean_CT2_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_mean_CT2_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_width_CT2_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_width_CT2_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg_lambda_CT2_SB2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg_lambda_CT2_SB2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_mean_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_mean_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_width_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_width_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_lambda_CT1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_lambda_CT1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_mean_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_mean_CT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_width_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_width_CT2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bkg2_lambda_CT2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooRealVar),-1,-1,1,"bkg2_lambda_CT2=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarRooJpsiJpsiFitCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncRooJpsiJpsiFit(void) {
   /* RooJpsiJpsiFit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit));
   G__memfunc_setup("RooJpsiJpsiFit",1407,G__RooJpsiJpsiFitCint_824_0_1, 105, G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("readData",790,G__RooJpsiJpsiFitCint_824_0_2, 85, G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooDataSet), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - dataFile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("readData",790,G__RooJpsiJpsiFitCint_824_0_3, 85, G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooDataSet), -1, 0, 1, 1, 1, 0, "u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 1 - dataFile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotData",825,G__RooJpsiJpsiFitCint_824_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 1 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDFmaker",746,G__RooJpsiJpsiFitCint_824_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 1 - filename u 'TString' - 0 - pdf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pureMCtoysGeneration",2087,G__RooJpsiJpsiFitCint_824_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fitData",701,G__RooJpsiJpsiFitCint_824_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 1 - dataFile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("embedMCtoysGeneration",2152,G__RooJpsiJpsiFitCint_824_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEmbedMCtoys",1499,G__RooJpsiJpsiFitCint_824_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initDataVars",1226,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("RooJpsiJpsiFit", 1407, G__RooJpsiJpsiFitCint_824_0_11, (int) ('i'), G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit), -1, 0, 1, 1, 1, 0, "u 'RooJpsiJpsiFit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~RooJpsiJpsiFit", 1533, G__RooJpsiJpsiFitCint_824_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__RooJpsiJpsiFitCint_824_0_13, (int) ('u'), G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit), -1, 1, 1, 1, 1, 0, "u 'RooJpsiJpsiFit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncRooJpsiJpsiFitCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalRooJpsiJpsiFitCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcRooJpsiJpsiFitCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__RooJpsiJpsiFitCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooRealVar = { "RooRealVar" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooArgSet = { "RooArgSet" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR = { "set<pair<RooAbsArg*,RooAbsArg*>,less<pair<RooAbsArg*,RooAbsArg*> >,allocator<pair<RooAbsArg*,RooAbsArg*> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR = { "deque<RooAbsCache*,allocator<RooAbsCache*> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooDataSet = { "RooDataSet" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_listlEdoublecOallocatorlEdoublegRsPgR = { "list<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR = { "vector<RooCurve*,allocator<RooCurve*> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RooCurve*,allocator<RooCurve*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooFormulaVar = { "RooFormulaVar" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR = { "list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR = { "pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >" , 115 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR = { "map<const RooAbsArg*,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > >,less<const RooAbsArg*>,allocator<pair<const RooAbsArg* const,pair<string,list<RooAbsReal::EvalError,allocator<RooAbsReal::EvalError> > > > > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_listlERooDataSetmUcOallocatorlERooDataSetmUgRsPgR = { "list<RooDataSet*,allocator<RooDataSet*> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR = { "map<int,string,less<int>,allocator<pair<const int,string> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR = { "vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR = { "reverse_iterator<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_dequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgR = { "deque<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >,allocator<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> > > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_stacklEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOdequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgRsPgR = { "stack<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >,deque<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> >,allocator<vector<RooMsgService::StreamConfig,allocator<RooMsgService::StreamConfig> > > > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR = { "map<string,basic_ostream<char,char_traits<char> >*,less<string>,allocator<pair<const string,basic_ostream<char,char_traits<char> >*> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR = { "RooCacheManager<vector<double,allocator<double> > >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR = { "list<RooArgSet*,allocator<RooArgSet*> >" , 99 , -1 };
G__linked_taginfo G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit = { "RooJpsiJpsiFit" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableRooJpsiJpsiFitCint() {
  G__RooJpsiJpsiFitCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TString.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooRealVar.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooArgSet.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooDataSet.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_listlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooFormulaVar.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_listlERooDataSetmUcOallocatorlERooDataSetmUgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_dequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_stacklEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOdequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR.tagnum = -1 ;
  G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableRooJpsiJpsiFitCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TString);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_RooRealVar);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_RooArgSet);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_RooDataSet);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_listlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_vectorlERooCurvemUcOallocatorlERooCurvemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooCurvemUcOallocatorlERooCurvemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_RooFormulaVar);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_listlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_pairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_maplEconstsPRooAbsArgmUcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRcOlesslEconstsPRooAbsArgmUgRcOallocatorlEpairlEconstsPRooAbsArgmUsPconstcOpairlEstringcOlistlERooAbsRealcLcLEvalErrorcOallocatorlERooAbsRealcLcLEvalErrorgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_listlERooDataSetmUcOallocatorlERooDataSetmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_vectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_reverse_iteratorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_dequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_stacklEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOdequelEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRcOallocatorlEvectorlERooMsgServicecLcLStreamConfigcOallocatorlERooMsgServicecLcLStreamConfiggRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_maplEstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcObasic_ostreamlEcharcOchar_traitslEchargRsPgRmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_RooCacheManagerlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__RooJpsiJpsiFitCintLN_listlERooArgSetmUcOallocatorlERooArgSetmUgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__RooJpsiJpsiFitCintLN_RooJpsiJpsiFit),sizeof(RooJpsiJpsiFit),-1,1280,(char*)NULL,G__setup_memvarRooJpsiJpsiFit,G__setup_memfuncRooJpsiJpsiFit);
}
extern "C" void G__cpp_setupRooJpsiJpsiFitCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupRooJpsiJpsiFitCint()");
  G__set_cpp_environmentRooJpsiJpsiFitCint();
  G__cpp_setup_tagtableRooJpsiJpsiFitCint();

  G__cpp_setup_inheritanceRooJpsiJpsiFitCint();

  G__cpp_setup_typetableRooJpsiJpsiFitCint();

  G__cpp_setup_memvarRooJpsiJpsiFitCint();

  G__cpp_setup_memfuncRooJpsiJpsiFitCint();
  G__cpp_setup_globalRooJpsiJpsiFitCint();
  G__cpp_setup_funcRooJpsiJpsiFitCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRooJpsiJpsiFitCint();
  return;
}
class G__cpp_setup_initRooJpsiJpsiFitCint {
  public:
    G__cpp_setup_initRooJpsiJpsiFitCint() { G__add_setup_func("RooJpsiJpsiFitCint",(G__incsetup)(&G__cpp_setupRooJpsiJpsiFitCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initRooJpsiJpsiFitCint() { G__remove_setup_func("RooJpsiJpsiFitCint"); }
};
G__cpp_setup_initRooJpsiJpsiFitCint G__cpp_setup_initializerRooJpsiJpsiFitCint;

